In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("heart.csv")

In [3]:
data

age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0     63    1                3         145          233                    1   
1     37    1                2         130          250                    0   
2     41    0                1         130          204                    0   
3     56    1                1         120          236                    0   
4     57    0                0         120          354                    0   
..   ...  ...              ...         ...          ...                  ...   
298   57    0                0         140          241                    0   
299   45    1                3         110          264                    0   
300   68    1                0         144          193                    1   
301   57    1                0         130          131                    0   
302   57    0                1         130          236                    0   

     restecg  max_hr  exang  oldpeak  slope  num_major_vessels  thal  target  
0          0     150      0      2.3      0                  0     1       1  
1          1     187      0      3.5      0                  0     2       1  
2          0     172      0      1.4      2                  0     2       1  
3          1     178      0      0.8      2                  0     2       1  
4          1     163      1      0.6      2                  0     2       1  
..       ...     ...    ...      ...    ...                ...   ...     ...  
298        1     123      1      0.2      1                  0     3       0  
299        1     132      0      1.2      1                  0     3       0  
300        1     141      0      3.4      1                  2     3       0  
301        1     115      1      1.2      1                  1     3       0  
302        0     174      0      0.0      1                  1     2       0  

[303 rows x 14 columns]

In [4]:
data.head()

age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0   63    1                3         145          233                    1   
1   37    1                2         130          250                    0   
2   41    0                1         130          204                    0   
3   56    1                1         120          236                    0   
4   57    0                0         120          354                    0   

   restecg  max_hr  exang  oldpeak  slope  num_major_vessels  thal  target  
0        0     150      0      2.3      0                  0     1       1  
1        1     187      0      3.5      0                  0     2       1  
2        0     172      0      1.4      2                  0     2       1  
3        1     178      0      0.8      2                  0     2       1  
4        1     163      1      0.6      2                  0     2       1

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   age                  303 non-null    int64  
 1   sex                  303 non-null    int64  
 2   chest_pain_type      303 non-null    int64  
 3   resting_bp           303 non-null    int64  
 4   cholestoral          303 non-null    int64  
 5   fasting_blood_sugar  303 non-null    int64  
 6   restecg              303 non-null    int64  
 7   max_hr               303 non-null    int64  
 8   exang                303 non-null    int64  
 9   oldpeak              303 non-null    float64
 10  slope                303 non-null    int64  
 11  num_major_vessels    303 non-null    int64  
 12  thal                 303 non-null    int64  
 13  target               303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [6]:
data.shape

(303, 14)

In [7]:
data.isnull().values.any()

False

In [8]:
data.isnull().sum()

age                    0
sex                    0
chest_pain_type        0
resting_bp             0
cholestoral            0
fasting_blood_sugar    0
restecg                0
max_hr                 0
exang                  0
oldpeak                0
slope                  0
num_major_vessels      0
thal                   0
target                 0
dtype: int64

In [9]:
X=data.drop(columns="target",axis=1)
Y=data['target']
data.isnull().sum()

age                    0
sex                    0
chest_pain_type        0
resting_bp             0
cholestoral            0
fasting_blood_sugar    0
restecg                0
max_hr                 0
exang                  0
oldpeak                0
slope                  0
num_major_vessels      0
thal                   0
target                 0
dtype: int64

In [10]:
print(X)

     age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0     63    1                3         145          233                    1   
1     37    1                2         130          250                    0   
2     41    0                1         130          204                    0   
3     56    1                1         120          236                    0   
4     57    0                0         120          354                    0   
..   ...  ...              ...         ...          ...                  ...   
298   57    0                0         140          241                    0   
299   45    1                3         110          264                    0   
300   68    1                0         144          193                    1   
301   57    1                0         130          131                    0   
302   57    0                1         130          236                    0   

     restecg  max_hr  exang  oldpeak  s

In [11]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(242, 13)
(61, 13)
(242,)
(61,)


In [13]:
from sklearn.ensemble._forest import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators= 10, criterion="entropy") 
classifier.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [14]:
y_pred= classifier.predict(X_test) 
y_pred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [15]:
# 0=having no heart disease
# 1=having heart disease


In [16]:
accuracy_score=(Y_test,y_pred)
accuracy_score

(179    0
 228    0
 111    1
 246    0
 60     1
       ..
 249    0
 104    1
 300    0
 193    0
 184    0
 Name: target, Length: 61, dtype: int64,
 array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64))

In [18]:
# Assuming you have trained the Random Forest Classifier and saved it as 'rf_classifier'

import numpy as np

input_data = np.array([[57, 0, 1, 130, 236, 0, 0, 174, 0, 0, 1, 1, 2]])  # Input data as a 2D array

predicted_output = classifier.predict(input_data)

if predicted_output == 0:
    print("Person does not have heart disease.")
else:
    print("Person has heart disease.")


Person does not have heart disease.


C:\Users\indna\anaconda3\envs\new_projects\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [19]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(Y_test, y_pred)
cm

array([[24,  5],
       [ 8, 24]], dtype=int64)

In [20]:
# Specify the file path for saving the pickle file
import pickle
file_path = 'heart.pkl'

# Save the trained classifier as a pickle file
with open(file_path, 'wb') as file:
    pickle.dump(classifier, file)
